# Generated by Django 2.2 on 2021-10-22 11:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0005_slotbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
