# Generated by Django 2.2 on 2021-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0011_auto_20211022_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
