# Generated by Django 2.2 on 2021-10-22 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0012_auto_20211022_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='user',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
