# Generated by Django 2.2 on 2021-10-23 13:58

import django.contrib.auth.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0013_auto_20211022_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
