# Generated by Django 2.2 on 2021-10-23 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0016_slotbooking_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='image',
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
