# Generated by Django 2.2 on 2021-10-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0017_auto_20211023_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='token',
            field=models.CharField(editable=False, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
