# Generated by Django 2.2 on 2021-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotbooking', '0018_auto_20211023_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='token',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
